/** A single user-facing action in the walkthrough */
export interface Step {
  id: string;
  order: number;
  action: "navigate" | "click" | "type" | "scroll" | "wait" | "assert" | "hover" | "screenshot";
  /** CSS selector or agent-browser element ref (e.g. @e12) */
  target?: string;
  /** Value for type actions, pixel amount for scroll, URL for navigate */
  value?: string;
  /** Narration text for this step */
  narration: string;
  /** How long to wait after this action before next step (ms) */
  pauseMs?: number;
}

/** Full walkthrough plan generated by LLM */
export interface ActionPlan {
  url: string;
  scenario: string;
  title: string;
  steps: Step[];
  totalDurationEstimate: number; // seconds
  /** Browser viewport to use */
  viewport?: { width: number; height: number };
}

/** Session state for a recording job */
export interface RecordingSession {
  id: string;
  status: "planning" | "approved" | "recording" | "narrating" | "assembling" | "done" | "failed";
  plan: ActionPlan;
  /** Path to raw screen recording */
  rawVideo?: string;
  /** Path to narration audio files (per step, by step id) */
  narrationFiles?: Record<string, string>;
  /** Path to final output */
  outputFile?: string;
  error?: string;
  progress: number; // 0-100
  createdAt: string;
}

/** Step result from agent-browser execution */
export interface StepResult {
  stepId: string;
  success: boolean;
  error?: string;
  /** DOM snapshot taken after action */
  snapshotPath?: string;
  /** Timestamp in the raw recording (seconds) */
  timestamp: number;
}
